<letters> ::= <letters><letter> | <letter>
<letter> ::= <g1> | <g2> | <g3> | <g4> | <g5>
<g1> ::= <g11> | <g12>
<g11> ::= a | b | c
<g12> ::= d | e | f
<g2> ::= <g21> | <g22> | <g23>
<g21> ::= g | h
<g22> ::= i | j | k | l
<g23> ::= m | n | o
<g3> ::= p | q | r | s | t
<g4> ::= <g41> | <g42>
<g41> ::= <g411> | <g412>
<g411> ::= u
<g412> ::= v | w
<g42> ::= x
<g5> ::= y | z
