<letters> ::= <letters><letter> | <letter>
<letter> ::= <consonant> | <vowel>
<vowel> ::= a | e | i | o | u
<consonant> ::= b | c | d | f | g | h | j | k | l | m | n | p | q | r | s | t | v | w | x | y | z
